DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:388 POST http://127.0.0.1:54222/session/bf355a5a90c672738801c3515c106310/window/maximize {}
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (5): 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/bf355a5a90c672738801c3515c106310/window/maximize'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB453D8208>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/bf355a5a90c672738801c3515c106310/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (6): 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/bf355a5a90c672738801c3515c106310/window/maximize'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB453F23C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/bf355a5a90c672738801c3515c106310/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (7): 127.0.0.1
DEBUG    urllib3.util.retry:retry.py:390 Incremented Retry for (url='/session/bf355a5a90c672738801c3515c106310/window/maximize'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING  urllib3.connectionpool:connectionpool.py:663 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FB453EDD88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/bf355a5a90c672738801c3515c106310/window/maximize
DEBUG    urllib3.connectionpool:connectionpool.py:208 Starting new HTTP connection (8): 127.0.0.1